package tuner

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"go/token"
	"sort"
	"strconv"
)

const (
	EngineCandidateBuildTag        = "tuner_candidate"
	EngineSeedBuildTag             = "tuner_seed"
	EngineCandidateGeneratedHeader = "// Code generated by cmd/tunerexport; DO NOT EDIT.\n"
	EngineSeedGeneratedHeader      = "// Code generated by cmd/tunerseed; DO NOT EDIT.\n"
)

type EngineCandidateMetadata struct {
	DatasetManifestSHA256 string
	Checkpoint            string
	RegistryFingerprint   string
}

// EngineSeedMetadata identifies the immutable candidate used to initialize a
// chained training stage. The seed overlay is intentionally a separate file
// and build tag from the child candidate overlay.
type EngineSeedMetadata struct {
	CandidateSHA256       string
	DatasetManifestSHA256 string
	Checkpoint            string
	CheckpointSHA256      string
	RegistryFingerprint   string
}

type goAssignment struct {
	symbol      string
	exportIndex int
	dimensions  []int
	value       int
}

// GenerateEngineCandidateSource emits indexed assignments under an opt-in
// build tag. Unowned storage cells retain their canonical engine values.
func GenerateEngineCandidateSource(registry *Registry, values []int, metadata EngineCandidateMetadata) ([]byte, error) {
	return generateEngineOverlaySource(registry, values, EngineCandidateGeneratedHeader, EngineCandidateBuildTag, []string{
		fmt.Sprintf("// Dataset manifest SHA-256: %s", metadata.DatasetManifestSHA256),
		fmt.Sprintf("// Registry fingerprint: %s", metadata.RegistryFingerprint),
		fmt.Sprintf("// Checkpoint: %s", metadata.Checkpoint),
	})
}

// GenerateEngineSeedSource emits the immutable parent overlay used by a
// chained run. It is deliberately incompatible with tuner_candidate so a
// process never sees both parent and child overlay semantics.
func GenerateEngineSeedSource(registry *Registry, values []int, metadata EngineSeedMetadata) ([]byte, error) {
	if !isSHA256(metadata.CandidateSHA256) || !isSHA256(metadata.DatasetManifestSHA256) ||
		!isSHA256(metadata.CheckpointSHA256) || !isSHA256(metadata.RegistryFingerprint) {
		return nil, errors.New("engine seed metadata requires SHA-256 identities")
	}
	return generateEngineOverlaySource(registry, values, EngineSeedGeneratedHeader, EngineSeedBuildTag, []string{
		fmt.Sprintf("// Parent candidate SHA-256: %s", metadata.CandidateSHA256),
		fmt.Sprintf("// Parent dataset manifest SHA-256: %s", metadata.DatasetManifestSHA256),
		fmt.Sprintf("// Parent registry fingerprint: %s", metadata.RegistryFingerprint),
		fmt.Sprintf("// Parent checkpoint SHA-256: %s", metadata.CheckpointSHA256),
		fmt.Sprintf("// Parent checkpoint: %s", metadata.Checkpoint),
	})
}

func generateEngineOverlaySource(registry *Registry, values []int, generatedHeader, buildTag string, metadata []string) ([]byte, error) {
	if registry == nil {
		return nil, errors.New("engine overlay generation requires a registry")
	}
	if len(values) != len(registry.Elements) {
		return nil, fmt.Errorf("exact parameter vector has length %d, want %d", len(values), len(registry.Elements))
	}
	assignments := make([]goAssignment, 0, len(values))
	seen := make(map[string]struct{}, len(values))
	for index, element := range registry.Elements {
		export := registry.Specs[element.SpecIndex].Export
		if !token.IsIdentifier(export.GoSymbol) {
			return nil, fmt.Errorf("export symbol %q is not a Go identifier", export.GoSymbol)
		}
		key := fmt.Sprintf("%s:%d", export.GoSymbol, element.ExportIndex)
		if _, exists := seen[key]; exists {
			return nil, fmt.Errorf("duplicate export storage slot %s", key)
		}
		seen[key] = struct{}{}
		assignments = append(assignments, goAssignment{
			symbol: export.GoSymbol, exportIndex: element.ExportIndex,
			dimensions: append([]int(nil), export.StorageDimensions...), value: values[index],
		})
	}
	sort.Slice(assignments, func(i, j int) bool {
		if assignments[i].symbol != assignments[j].symbol {
			return assignments[i].symbol < assignments[j].symbol
		}
		return assignments[i].exportIndex < assignments[j].exportIndex
	})

	var source bytes.Buffer
	fmt.Fprint(&source, generatedHeader)
	fmt.Fprintf(&source, "//go:build %s\n\n", buildTag)
	fmt.Fprintln(&source, "package engine")
	fmt.Fprintln(&source)
	for _, line := range metadata {
		fmt.Fprintln(&source, line)
	}
	fmt.Fprintln(&source, "func init() {")
	for _, assignment := range assignments {
		target := assignment.symbol
		if len(assignment.dimensions) == 0 {
			if assignment.exportIndex != 0 {
				return nil, fmt.Errorf("scalar symbol %q has export index %d", assignment.symbol, assignment.exportIndex)
			}
		} else {
			coordinates, err := flattenedCoordinates(assignment.exportIndex, assignment.dimensions)
			if err != nil {
				return nil, fmt.Errorf("symbol %q: %w", assignment.symbol, err)
			}
			for _, coordinate := range coordinates {
				target += "[" + strconv.Itoa(coordinate) + "]"
			}
		}
		fmt.Fprintf(&source, "\t%s = %d\n", target, assignment.value)
	}
	fmt.Fprintln(&source, "}")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated engine candidate: %w", err)
	}
	return formatted, nil
}

func flattenedCoordinates(index int, dimensions []int) ([]int, error) {
	if index < 0 {
		return nil, fmt.Errorf("negative flattened index %d", index)
	}
	total := 1
	for _, dimension := range dimensions {
		if dimension <= 0 {
			return nil, fmt.Errorf("invalid storage dimension %d", dimension)
		}
		total *= dimension
	}
	if index >= total {
		return nil, fmt.Errorf("flattened index %d outside storage size %d", index, total)
	}
	coordinates := make([]int, len(dimensions))
	for axis := len(dimensions) - 1; axis >= 0; axis-- {
		coordinates[axis] = index % dimensions[axis]
		index /= dimensions[axis]
	}
	return coordinates, nil
}
